services:
  - type: web
    name: helloheads-api
    runtime: docker
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0

